Add Prinsess.
Yaroslav131/Home-Work pull request #1
Opened 2020-12-03 14:26 UTC by Yaroslav131

2020-12-03 22:32 UTC, BitW13 commented on Prinsess/Field/Fields.cs
> +        public void CreatField()
CreateField

2020-12-03 22:32 UTC, BitW13 commented on Prinsess/Field/Field.csproj
> +
![image](https://user-images.githubusercontent.com/28789651/101096337-7bb71d80-35d0-11eb-8f1e-020ee3bb4aea.png)
Нужно создавать не библиотеки, а классы

2020-12-04 15:18 UTC, AnastasiaKorotkevich commented on Prinsess/Prinsess/GameFunc.cs
> +        public void Reset()
Отступ.

2020-12-04 15:18 UTC, AnastasiaKorotkevich commented on Prinsess/Prinsess/GameFunc.cs
> +            Thread.Sleep(2000);
Зачем это?

2020-12-04 15:18 UTC, AnastasiaKorotkevich commented on Prinsess/Prinsess/GameFunc.cs
> +            do
Отступ.

2020-12-04 15:18 UTC, AnastasiaKorotkevich commented on Prinsess/Prinsess/MineTrap.cs
> +    public class MineTrap
Название не походит. МинаЛовушка?

2020-12-04 15:18 UTC, AnastasiaKorotkevich commented on Prinsess/Prinsess/Program.cs
> +    class Program
Модификатор.

2020-12-04 15:18 UTC, AnastasiaKorotkevich commented on Prinsess/Prinsess/Program.cs
> +        static void Main(string[] args)
Модификатор.

2020-12-04 15:18 UTC, AnastasiaKorotkevich commented on Prinsess/Prinsess/Value.cs
> +        public const int heroStartOy = 1;
Как надо называть константы?

2020-12-04 16:38 UTC, Yaroslav131 commented on Prinsess/Prinsess/GameFunc.cs
> +            Thread.Sleep(2000);
Ну, я это добавил ,чтобы массив сразу не закрывался, и игрок успел увидеть где он стал на ловушку, ведь он может быстро идти и не заметить

2020-12-04 21:49 UTC, BitW13 commented on Prinsess/Prinsess/GameFunc.cs
> +            } while (Values.UnknownKey);
while на новую строку

2020-12-04 21:49 UTC, BitW13 commented on Prinsess/Prinsess/GameFunc.cs
> +            Thread.Sleep(2000);
Лучше убрать

2020-12-04 21:49 UTC, BitW13 commented on Prinsess/Prinsess/Trap.cs
> +    public class Mine
![image](https://user-images.githubusercontent.com/28789651/101217936-3dcefd80-3693-11eb-94a3-f15837756694.png)
Проблемка....
Название должно быть одно

2020-12-04 21:49 UTC, BitW13 commented on Prinsess/Prinsess/Trap.cs
> +using System;
Добавь отступ после юзингов

2020-12-04 21:49 UTC, BitW13 commented on Prinsess/Prinsess/Trap.cs
> +        public void CreateMinField()
Create..Min? что min?

2020-12-04 21:49 UTC, BitW13 commented on Prinsess/Prinsess/Value.cs
> +    public class Values
![Uploading image.png…]()

2020-12-04 21:49 UTC, BitW13 commented on Prinsess/Prinsess/Value.cs
> +    {
И мне не нравится, что везде используется какое-то поле из этого класса
Тупо God-class
Это не нормальная абстракция

2020-12-04 21:51 UTC, BitW13 commented on Prinsess/Prinsess/Value.cs
> +    public class Values
А почему не static?

2020-12-05 07:29 UTC, Yaroslav131 commented on Prinsess/Prinsess/Value.cs
> +    public class Values
здесь должна быть фото наверное , но у меня не отгружаает

2020-12-06 14:37 UTC, AnastasiaKorotkevich reviewed
Это что за пиздец?

2020-12-06 14:40 UTC, BitW13 reviewed
Поправь
Класс -- это какой-то сакет объектов из реального мира, абстракция какая-то
Зачем разделять данные и методы?
Это должно быть вместе

2020-12-06 14:40 UTC, BitW13 commented on Prinsess/Prinsess/Field/FieldValues.cs
> +    public static class FieldValue
Почему нельзя объединить FieldValue и Field класс??
И остальные также?

2020-12-06 21:14 UTC, AnastasiaKorotkevich requested changes

2020-12-06 21:14 UTC, AnastasiaKorotkevich commented on Prinsess/Prinsess/GameFunc.cs
> +        public void EndCodition()
Как переводится название метода? И подходит ли в этом случае?

2020-12-06 21:14 UTC, AnastasiaKorotkevich commented on Prinsess/Prinsess/GameFunc.cs
> +    public class GameFunction
Название для класса максимально странное. Почему не просто Game?

2020-12-06 21:14 UTC, AnastasiaKorotkevich commented on Prinsess/Prinsess/GameFunc.cs
> +        public void Reset()
Reset чего?

2020-12-06 21:14 UTC, AnastasiaKorotkevich commented on Prinsess/Prinsess/Program.cs
> +                    gameField.TotalField[Hero.Oy, Hero.Ox] = Hero.HeroAvatar;
13 строчка. Модификатор?

2020-12-06 21:14 UTC, AnastasiaKorotkevich commented on Prinsess/Prinsess/Program.cs
> +                    gameField.TotalField[Hero.Oy, Hero.Ox] = Hero.HeroAvatar;
34 строчка. Отступ?

2020-12-06 21:14 UTC, AnastasiaKorotkevich commented on Prinsess/Prinsess/Program.cs
> +                    if (gameField.TotalField[Hero.Oy, Hero.Ox] == gameField.TotalField[Prinses.PrinsessPossitionOx, Prinses.PrinsessPossitionOy])
Отступ?

2020-12-06 21:14 UTC, AnastasiaKorotkevich commented on Prinsess/Prinsess/Program.cs
> +                    if (gameField.TotalField[Hero.Oy, Hero.Ox] != Mine.MineAvatar)
Отступ?

2020-12-06 21:14 UTC, AnastasiaKorotkevich commented on Prinsess/Prinsess/Program.cs
> +            } while (GameFunction.ExitGame);
while на новую строку разве не нужно переносить?

2020-12-06 21:14 UTC, AnastasiaKorotkevich commented on Prinsess/Prinsess/Hero.cs
> +        public static int Oy { get; set; }
Смущает Ox, Oy. Почему бы не назвать это координатами X и Y?

2020-12-06 22:58 UTC, merged